import Link from "next/link"
import { ShieldCheckIcon } from "lucide-react"

const LINKS = [
  { href: "/playground", label: "Scanner" },
  { href: "/benchmarks", label: "Benchmarks" },
  { href: "/sqli", label: "SQLi Engine" },
]

export function SiteFooter() {
  return (
    <footer className="mt-24 border-t border-foreground/10 bg-background/40 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl flex-col gap-8 px-4 py-10 md:flex-row md:items-start md:justify-between md:px-8">
        <div className="flex max-w-md flex-col gap-3">
          <div className="flex items-center gap-2.5">
            <span className="flex size-8 items-center justify-center rounded-lg bg-linear-to-br from-primary to-accent text-primary-foreground">
              <ShieldCheckIcon className="size-4" aria-hidden="true" />
            </span>
            <span className="font-mono text-sm font-bold tracking-[0.18em]">AEGIS-AC</span>
          </div>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Reference implementation of an automata-theoretic network IDS. Numbers come from{" "}
            <code className="font-mono text-foreground">REPORT.md</code>, generated by{" "}
            <code className="font-mono text-foreground">bench/report.py</code>.
          </p>
        </div>
        <nav aria-label="Footer" className="flex flex-col gap-2 text-sm">
          <span className="font-mono text-xs tracking-[0.2em] text-muted-foreground uppercase">Explore</span>
          {LINKS.map((l) => (
            <Link key={l.href} href={l.href} className="text-foreground/80 transition-colors hover:text-primary">
              {l.label}
            </Link>
          ))}
        </nav>
      </div>
      <div className="border-t border-foreground/5">
        <p className="mx-auto max-w-7xl px-4 py-4 text-xs text-muted-foreground md:px-8">
          SQLi corpus: libinjection test data (Nick Galbreath, BSD-3-Clause).
        </p>
      </div>
    </footer>
  )
}
