export function SiteFooter() {
  return (
    <footer className="border-t">
      <div className="mx-auto flex max-w-6xl flex-col gap-2 px-4 py-6 text-xs text-muted-foreground md:flex-row md:items-center md:justify-between md:px-6">
        <p>
          AEGIS-AC reference implementation. Numbers come from{" "}
          <code className="font-mono text-foreground">REPORT.md</code>, generated by{" "}
          <code className="font-mono text-foreground">bench/report.py</code>.
        </p>
        <p>SQLi corpus: libinjection test data (Nick Galbreath, BSD-3-Clause).</p>
      </div>
    </footer>
  )
}
