// Values transcribed from REPORT.md (generated by bench/report.py). Regenerate the report with
// ./run_benchmarks.sh and update these tables to keep the console in sync.

export const SYSTEMS = {
  AEGIS_AC: "AEGIS-AC",
  NAIVE_MULTIPATTERN: "Naive multi-pattern",
  STANDARD_AC: "pyahocorasick",
  HYPERSCAN_SURICATA: "Hyperscan",
} as const

export type SystemKey = keyof typeof SYSTEMS

export const memoryByK = [
  { k: 100, sumLen: 1401, meanLen: 14.0, states: 1079, ratio: 0.77, denseMiB: 1.1, classMiB: 0.2 },
  { k: 300, sumLen: 4188, meanLen: 14.0, states: 3066, ratio: 0.732, denseMiB: 3.0, classMiB: 0.9 },
  { k: 1000, sumLen: 13660, meanLen: 13.7, states: 9639, ratio: 0.706, denseMiB: 9.4, classMiB: 3.7 },
  { k: 3000, sumLen: 41860, meanLen: 14.0, states: 29444, ratio: 0.703, denseMiB: 28.8, classMiB: 13.0 },
  { k: 10000, sumLen: 141730, meanLen: 14.2, states: 98822, ratio: 0.697, denseMiB: 96.5, classMiB: 43.5 },
]

export const baselines: {
  k: number
  system: SystemKey
  meanNs: number
  p99Ns: number
  gbps: number
}[] = [
  { k: 100, system: "AEGIS_AC", meanNs: 246593, p99Ns: 532691, gbps: 0.07 },
  { k: 100, system: "NAIVE_MULTIPATTERN", meanNs: 69503, p99Ns: 73625, gbps: 0.22 },
  { k: 100, system: "STANDARD_AC", meanNs: 22531, p99Ns: 27489, gbps: 0.67 },
  { k: 100, system: "HYPERSCAN_SURICATA", meanNs: 7856, p99Ns: 11910, gbps: 2.18 },
  { k: 1000, system: "AEGIS_AC", meanNs: 227662, p99Ns: 462934, gbps: 0.07 },
  { k: 1000, system: "NAIVE_MULTIPATTERN", meanNs: 718931, p99Ns: 941774, gbps: 0.02 },
  { k: 1000, system: "STANDARD_AC", meanNs: 49041, p99Ns: 54992, gbps: 0.3 },
  { k: 1000, system: "HYPERSCAN_SURICATA", meanNs: 3184, p99Ns: 3843, gbps: 4.64 },
  { k: 10000, system: "AEGIS_AC", meanNs: 201895, p99Ns: 239253, gbps: 0.07 },
  { k: 10000, system: "NAIVE_MULTIPATTERN", meanNs: 7262625, p99Ns: 8986101, gbps: 0.0 },
  { k: 10000, system: "STANDARD_AC", meanNs: 48102, p99Ns: 57415, gbps: 0.31 },
  { k: 10000, system: "HYPERSCAN_SURICATA", meanNs: 11963, p99Ns: 13379, gbps: 1.33 },
]

export const selectivity = [
  { anchorLen: 2, hits: 167017, rate: 0.835085 },
  { anchorLen: 3, hits: 11704, rate: 0.05852 },
  { anchorLen: 4, hits: 175, rate: 0.000875 },
  { anchorLen: 5, hits: 25, rate: 0.000125 },
  { anchorLen: 8, hits: 21, rate: 0.000105 },
  { anchorLen: 20, hits: 21, rate: 0.000105 },
]

export const fragmentation = [
  { rate: 0.0, fragmented: 1.0, full: 1.0 },
  { rate: 0.1, fragmented: 1.0, full: 1.0 },
  { rate: 0.3, fragmented: 1.0, full: 1.0 },
  { rate: 0.5, fragmented: 1.0, full: 1.0 },
]

export const redos = [
  { n: 10, aegisUs: 46.0, backtrackMs: 0.1 },
  { n: 15, aegisUs: 22.6, backtrackMs: 2.7 },
  { n: 18, aegisUs: 23.8, backtrackMs: 17.3 },
  { n: 20, aegisUs: 29.4, backtrackMs: 110.4 },
  { n: 22, aegisUs: 65.1, backtrackMs: 310.6 },
]

export const storageLayout = [
  { k: 100, layout: "dense", states: 1079, entries: 256, memoryMiB: 1.05, nsPerByte: 135.6 },
  { k: 100, layout: "class_reduced", states: 1079, entries: 115, memoryMiB: 0.47, nsPerByte: 176.64 },
  { k: 1000, layout: "dense", states: 9639, entries: 256, memoryMiB: 9.41, nsPerByte: 235.45 },
  { k: 1000, layout: "class_reduced", states: 9639, entries: 226, memoryMiB: 8.31, nsPerByte: 182.14 },
]

export const sqliCorpus = {
  malicious: {
    n: 85791,
    strictCatch: 9396,
    miss: 99,
    unparseable: 76296,
    strictRecall: 0.11,
    lenientRecall: 0.999,
  },
  benign: {
    n: 421,
    correct: 24,
    falsePositive: 17,
    unparseable: 380,
    fpRate: 0.0404,
  },
  elapsedS: 27.14,
  falsePositives: [
    "TRUE#LAST",
    "LOCK AND KEY",
    "40 AND FAB",
    "7 AND HALF",
    "00 AND 3",
    "10.00 AND UNDER",
    "10 OR LESS",
    "(NEW AND UNIQUE)",
    "9/PLUGS AND TUNNELS",
    "BAMBOO CHARCOAL SOAP 1 '#",
  ],
}

export const modules = [
  { id: 1, name: "AC Prefilter Engine", owner: "Core Automaton Lead", path: "ac_prefilter/", tests: 13 },
  { id: 2, name: "Rule Loader & Regex Compiler", owner: "Compiler Lead", path: "rule_compiler/", tests: 20 },
  { id: 3, name: "SQLi Lexer & DPDA Recognizer", owner: "Scanner/Demo Lead", path: "sqli_engine/", tests: 13 },
  { id: 4, name: "Flow State, Alerts, Orchestrator", owner: "Integration Lead", path: "pipeline/", tests: 14 },
  { id: 5, name: "Instrumentation & Benchmarks", owner: "Benchmarking Lead", path: "bench/", tests: 18 },
]

export const sqliVerdicts = [
  {
    label: "UNION injection",
    staticPart: "SELECT * FROM t WHERE id = ",
    tainted: "1 UNION SELECT a FROM b",
    suffix: "",
    isAttack: true,
  },
  {
    label: "OR tautology",
    staticPart: "SELECT * FROM t WHERE name = ",
    tainted: "'x' OR 'a'='a'",
    suffix: "",
    isAttack: true,
  },
  {
    label: "Benign arithmetic",
    staticPart: "",
    tainted: "SELECT (1+2)*3",
    suffix: "",
    isAttack: false,
  },
  {
    label: "Benign nested subquery",
    staticPart: "SELECT * FROM t WHERE id IN (SELECT id FROM u WHERE flag = ",
    tainted: "42",
    suffix: ")",
    isAttack: false,
  },
]
